<Project>
  <Sdk Name="Microsoft.NET.Sdk" />
  <Sdk Name="ktsu.Sdk" />
  <ItemGroup>
    <PackageReference Include="DotNet.Glob" />
    <PackageReference Include="ktsu.Extensions" />
    <PackageReference Include="ktsu.FuzzySearch" />
    <PackageReference Include="Polyfill" PrivateAssets="all" />
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
  </ItemGroup>
</Project>
